replicaCount: 1

image:
  repository: homeassistant/home-assistant
  tag: "2025.10"
  pullPolicy: IfNotPresent

persistence:
  hostPath: /mnt/homeassistant
  size: 5Gi

usbDevice:
  hostPath: /dev/ttyUSB0

service:
  type: ClusterIP
  port: 8123

ingress:
  enabled: true
  className: "trefik" # Cambia esto seg√∫n tu Ingress Controller (traefik, nginx, etc.)
  annotations:
    kubernetes.io/ingress.class: traefik
    # cert-manager.io/cluster-issuer: "letsencrypt-prod" # Si usas SSL
  hosts:
    - host: homeassistant
      paths:
        - path: /
          pathType: ImplementationSpecific