apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "homeassistant.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      hostNetwork: true  # Equivale a network_mode: host
      containers:
        - name: homeassistant
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          securityContext:
            privileged: true # Equivale a privileged: true
          volumeMounts:
            - name: config
              mountPath: /config
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
            - name: usb
              mountPath: {{ .Values.usbDevice.hostPath }}
            - name: dbus
              mountPath: /run/dbus
              readOnly: true
          # Mapeo de dispositivos
          resources: {}
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: {{ include "homeassistant.fullname" . }}-pvc
        - name: localtime
          hostPath:
            path: /etc/localtime
            type: File
        - name: usb
          hostPath:
            path: {{ .Values.usbDevice.hostPath }}
        - name: dbus
          hostPath:
            path: /run/dbus
            type: Directory