apiVersion: v1
kind: Service
metadata:
  name: {{ include "homeassistant.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8123
      protocol: TCP
      name: http
  selector:
    app: homeassistant
